package com.ngarvey.chitchat

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import com.ngarvey.chitchat.ui.main.MainFragment

/**
 * Basic SFA activity component
 * Auto-generated by Android Studio
 */
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.main_activity)
        if (savedInstanceState == null) {
            supportFragmentManager.beginTransaction()
                .replace(R.id.container, MainFragment.newInstance())
                .commitNow()
        }
    }

}
